---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: .docs-builder.tpl
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: terraform
    schedule:
      interval: daily
