---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      containers:
        - name: docs
          image: kzitnomovdnagbuwkmgltxbxv.azurecr.io/docs:0.0.4
          ports:
            - containerPort: 8080
